import React from "react";
import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header";
import StoreProvider from "@/providers/store-provider";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS ? (
        <GoogleAnalytics
          measurementId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}
        />
      ) : null}
      <body>
        <StoreProvider>
          <Header />
          <main>{children}</main>
        </StoreProvider>
        <Analytics />
      </body>
    </html>
  );
}
